[FEAT1] : multi-step-from : step1 ~ step2
JunnieLee/web-standards-considered-components pull request #2
Opened 2024-04-10 13:52 UTC by JunnieLee

# 💬 
- 코드가 너무 더러운것같아 찝찝하지만 또 정리하다보면 정작 중요한게 계속 미뤄질것같아 당장은 그대로 두었습니다!
조금씩 작업하면서 다듬어나가 보겠습니다 :)
- toggle 쪽 label css 작업때문에 세시간이 넘는 삽질을 하였습니다 ㅠ
  - 액션 아이템 : 삽질 줄이기-> 30분이 넘어간다 싶으면 잘못 되어가고 있다 판단하고 바로 도움 청하기

# 스크린샷 📷 
![image](https://github.com/JunnieLee/web-standards-considered-components/assets/33515577/129292f9-c028-4fd5-8310-4f16f8365b4c)

![image](https://github.com/JunnieLee/web-standards-considered-components/assets/33515577/4ba21452-bd10-465e-8b87-ecf79b781ade)

2024-04-13 10:13 UTC, twinstae requested changes
고생하셨습니다. 웹표준을 이용한 폼 제작의 기본적인 개념은 익혀가시는듯 합니다.

CSS도 보니까 교정할 습관들이 좀 보이네요. (absolute의 남용이나. width를 고정값으로 줄 때의 문제. flex gap보다 margin이 많이 쓰인다거나) css는 다음에 고쳐보도록 하고요.

일단 이 친구 기본을 마치시면 그 다음에는 폼 검증으로 들어가면 좋겠습니다.

2024-04-13 10:13 UTC, twinstae commented on app/multi-step-form/_components/FormStepOne.tsx
> +        <section className={styles.mainContent}>
section은 div가 아니기 때문에 자기 제목도 없고 다른 부분과 구분할 필요도 없을 때 쓰면 안 됩니다. div 로 처리해도 괜찮겠습니다~

https://developer.mozilla.org/ko/docs/Web/HTML/Element/section
각각의 `<section>`을 식별할 수단이 필요합니다. 주로 제목(`<h1>-<h6>`) 요소를 `<section>`의 자식으로 포함하는 방법을 사용합니다.
요소의 콘텐츠를 따로 구분해야 할 필요가 있으면 `<article>` 요소를 고려하세요.
`<section>` 요소를 일반 컨테이너로 사용하지 마세요. 특히 단순한 스타일링이 목적이라면 `<div>` (en-US) 요소를 사용해야 합니다.

2024-04-13 10:13 UTC, twinstae commented on app/multi-step-form/_components/FormStepOne.tsx
> +      aria-current={step === 1 ? "step" : "false"}
Step의 로직이 복잡한데 Step one, two, three에 중복되고 있죠? 보통은 이런 멀티 스텝 폼을 추상화해서 컴포넌트로 만듭니다. h3와 p까지 추상화하면 더 강력할텐데. 다만 그러려면 디자인에 제약도 생기죠.

그게 아니면 Context Api를 써서 compound component로 만들 수 있겠습니다.

2024-04-13 10:13 UTC, twinstae commented on app/multi-step-form/_components/FormContainer.tsx
> +          router.push("/multi-step-form?step=1");
옹. 이렇게 onSubmit과 goBack 을 위에서 내려주면, 전체 흐름을 컴포넌트를 사용하는 쪽에서 관리할 수 있어서 좋네요.

좀 아쉬운 점은 뒤로가기인데 꼭 push를 써야 할까 입니다. push로 뒤로가기를 하다가 브라우저나 안드로이드의 뒤로가기 버튼을 누르면 어떻게 될지 한 번 생각해보시면 ^^

2024-04-13 10:13 UTC, twinstae commented on app/multi-step-form/_components/FormContainer.tsx
> +  const leftNavigation = (
컴포넌트 안에서 jsx 변수를 만들기보다는 보통은 자기 컴포넌트로 분리되는 게 더 좋습니다. (왜 그럴까요? 한 번 생각해보시면)

2024-04-13 10:13 UTC, twinstae commented on app/multi-step-form/_components/FormStepThree.tsx
> +            <section className={styles.column}>
위에서도 말했지만 section을 남용하면 안 됩니다. 스타일을 넣고 싶다면 div면 충분할듯 합니다.

2024-04-13 10:13 UTC, twinstae commented on app/multi-step-form/_components/formContainer.module.css
> +.hidden {
일단 이름이 hidden이라 하면 hidden을 하는 방법이 다양하기 때문에 구분하면 좋겠습니다. display: hidden 으로 오해하기 쉬울듯 합니다.

한편으로 아쉬운 점은 이 친구는 특정 페이지에서만 쓰이는 게 아닌데. css module에 넣으면 다른 페이지가 생기면 css가 점점 중복되지 않을까요?

2024-04-13 10:13 UTC, twinstae commented on app/globals.css
> +label:has(input[type="radio"]:checked) {
이 친구는 css module에 들어가야 하겠습니다.

2024-04-13 10:13 UTC, twinstae commented on app/multi-step-form/_components/formContainer.module.css
> +  font-weight: 600;
사실 이 방식은 좀 문제가 있습니다. 둘 중에 무엇이 선택된 것인지 시각적으로만 구분이 가거든요. 체크박스가 체크되었다는 게 무슨 의미인지 시각 장애인 분들은 알 도리가 없습니다.

그래서 제 생각에 이 친구는 보기와는 달리 radio로 해석하고, 양쪽에 있는 건 radio의 label로 보는 게 더 타당하지 않을까 싶네요. (그러면 가운데 친구를 클릭했을 때 radio가 토글 되는 건 어떻게 구현할지 생각해보시면 ^^)

2024-04-14 06:33 UTC, JunnieLee commented
> 고생하셨습니다. 웹표준을 이용한 폼 제작의 기본적인 개념은 익혀가시는듯 합니다.
> 
> CSS도 보니까 교정할 습관들이 좀 보이네요. (absolute의 남용이나. width를 고정값으로 줄 때의 문제. flex gap보다 margin이 많이 쓰인다거나) css는 다음에 고쳐보도록 하고요.
> 
> 일단 이 친구 기본을 마치시면 그 다음에는 폼 검증으로 들어가면 좋겠습니다.

헉 맞아요 말씀주신 부분들 다 제가 메인으로 쓰고 있는 습관들입니다 ㅠ 어떤 좋은 대안들이 있는지 몰라 항상 저렇게 쓰고, UI 깨지면 삐질삐질 하고 했었는데, 요거 관련해서도 한번 말씀나누고 피드백 받을 수 있으면 좋을것 같습니다! @twinstae 🐰 👍 ✨

2024-04-14 06:40 UTC, JunnieLee commented on app/multi-step-form/_components/FormStepOne.tsx
> +        <section className={styles.mainContent}>
호오 제가 section 개념에 대해 잘못 이해하고있었나봅니다.. 시멘틱하게 하려면 div대신 section을 써야한다고 생각했네요.. (같은 기능이지만 section이 좀더 시멘틱하다고 생각하고 있었던...) 문서들도 읽어보았지만 아직까지는 section과 article div 다 좀 헷갈리는것같습니다 (정확히 어떤 상황에서 어떤놈을 사용해야하는지)..! 다만 적어도 이쪽 코드에서는 스타일링을 위해 따로 덩어리를 나눈것이므로 말씀대로 div가 적절할것같습니다 ㅎㅎ

2024-04-14 06:45 UTC, JunnieLee commented on app/multi-step-form/_components/FormStepOne.tsx
> +        <section className={styles.mainContent}>
✅ **수정완료** ([커밋 링크](https://github.com/JunnieLee/web-standards-considered-components/pull/2/commits/78cbd3ca0194f170a464083cb6cf6158dde2c487))

2024-04-14 06:53 UTC, JunnieLee commented on app/multi-step-form/_components/FormContainer.tsx
> +          router.push("/multi-step-form?step=1");
전에 모바일개발에서는 navigation stack pop을 해주었는데, next.js router에서 goBack 처리를 어떻게 하나 찾아봤더니, `router.back()` 을 이용해 처리가 가능하다고 하네요?! 🧚 

근데 이렇게 하면, 1단계 선택해서 입력하고, 왼편 nav list 를 통해 3단계를 작성하다 <이전 단계>를 클릭하면 2단계가 아닌 1단계로 가게 되어서, 그런 사이드이펙트(?)를 방지하기 위해서는 특정 주소를 지정해줘야하지 않을까 생각이 듭니다..! 대신 push말고 replace로 하면 불필요한 스택을 쌓지 않을 수 있을것같은데, `router.replace`로 처리해주는건 혹시 어떻게 생각하시나요?! @twinstae

2024-04-14 07:13 UTC, JunnieLee commented on app/multi-step-form/_components/FormContainer.tsx
> +  const leftNavigation = (
@twinstae 
흠.. 테스트 가능성 때문일까요...? 그치만 컴포넌트 관련 테스트를 짜본적이 없어서 자세히는 모르겠습니다...! 🤣 

항상 재활용될 가능성이 없어보이면 컴포넌트로 나누기보다는 그냥 내부에 jsx변수로 따로 분리했었는데.. 
장점을 생각해보자면... React.memo 등을 통해 불필요한 렌더링을 방지할 수 있다 정도?!

혹시 또 다른 이유가 있을까요~?! 🕵️ ✨

2024-04-14 07:15 UTC, JunnieLee commented on app/multi-step-form/_components/FormStepThree.tsx
> +            <section className={styles.column}>
@twinstae  오옹 근데 이부분은 의미상 나뉘는 덩어리 부분이기도 하고 내부에 h4도 있어서 `<section>`으로 사용되어도 되지 않을까 싶었는데 그래도 최대한 `<div>`로 할 수 있는 부분은 `<div>`를 사용하고 `<section>` 사용을 최소화 하는게 좋을까요?!!

2024-04-14 08:42 UTC, twinstae commented on app/multi-step-form/_components/FormContainer.tsx
> +          router.push("/multi-step-form?step=1");
음 말씀하신 경우는 사이드 이펙트가 아니라 웹에서는 올바른 동작입니다. replace를 쓰는 것도 나름의 역설을 낳는데요. 예를 들어 좌측 네비게이션을 통해서 1 -> 3 -> 2 로 간 뒤에 뒤로 가기를 하면 히스토리에 1 -> 3 -> 1 처럼 남게 됩니다. 그 상태로 브라우저 뒤로가기를 하면? 3으로 가죠.

사실 이것은 근본적으로 웹의 히스토리 관리 방식이 앱과 다르기 때문입니다. 히스토리 스택을 각 단계별로만 생각하면 이상한 게 많이 생깁니다.

2024-04-14 08:48 UTC, twinstae commented on app/multi-step-form/_components/FormContainer.tsx
> +  const leftNavigation = (
저는 재사용이 정말 안 좋은 말이라 생각합니다. 모든 걸 재사용을 기준으로 사람들에게 생각하게 만드는데. 역할이 보통은 더 좋은 표현이 아닐까 싶네요. 메모를 쓰는 것도 보통은 안 좋은 관습이죠.

설명하자면 이렇습니다. 컴포넌트 안에 jsx 변수를 넣는 건 클로저를 이용하고 prop으로 넘기는 게 귀찮아서 그런 경우가 많은데요. 서로 다른 역할이 하나의 컴포넌트에 뭉쳐지게 만들고, 의존성이 명확하게 드러나지 않게 됩니다.

그래서 컴포넌트를 나눌 때에는 역할을 기준으로 나누는 게 보통 좋습니다. 이 컴포넌트의 구체적인 구현이 궁금하지 않으면 건너 뛸 수 있고, 어떤 의존성이 있는지 명시적으로 드러나도록 말이죠.

그리고 리액트는 jsx 변수와 컴포넌트 렌더를 다르게 취급합니다. <LeftSide /> 와 {leftSide}는 여러모로 다른 결과를 낳지요.

2024-04-14 08:52 UTC, twinstae commented on app/multi-step-form/_components/FormStepThree.tsx
> +            <section className={styles.column}>
최소화하는 게 좋은 그런 느낌은 아니고요. section에 h4 가 있으니까 써도 된다는 그런 규칙도 아닙니다.

h4가 누구의 제목인지 생각해보면 저 라벨, 체크박스의 이름입니다. 이미 라벨 3개가 서로를 구분하고 있기 때문에 section을 쓰지 않아도 구분이 됩니다. section 대신 div를 여기서 쓰는 것은 보통 section보다 div가 좋다는 게 아니고. label이 서로 구분하는 역할을 하고 있으니 label 안에서 스타일링을 할 용도로는 div만 쓰면 되기 때문인 것이죠.

그 표준의 설명을 기계적으로 받아들이기 보다는 목적을 생각해서 쓰시면 좋을듯 합니다. 시맨틱은 어떤 태그를 기계적으로 적용하는 게 아니라, 문장기호나 문법처럼 도구거든요. 기계들에게 이 친구들은 분리된 구획이야! 라는 걸 보여주고 싶은데 li나 label이나 다른 대안이 없을 때 section을 쓰는 것입니다.

2024-04-14 09:55 UTC, JunnieLee commented on app/multi-step-form/_components/FormContainer.tsx
> +          router.push("/multi-step-form?step=1");
흠... 정말 말씀주신 케이스를 생각하면 replace를 쓴다고 해서 제가 원하는 방식으로 제어할 수 있진 않겠네요 🤨 그럼 <이전 단계> 버튼이 클릭되었을때 순서상의 직전 단계(ex.3->2, 2->1)가 아닌, 네비게이션 상의 직전 단계 (ex. 1->3 으로 이동한 상태라면 다시 1로) 로 이동하는게 웹에서는 자연스러운 동작이고, 따라서 router.back 을 쓰는게 적절한 해결방안이 되는걸로 이해하면 될까요~?! ✨ @twinstae

2024-04-14 11:41 UTC, JunnieLee commented on app/multi-step-form/_components/FormContainer.tsx
> +  const leftNavigation = (
**"컴포넌트를 나눌 때에는 역할을 기준으로 나눈다"** -> 말씀주신대로 앞으로는 이 기준으로 컴포넌트로 뺄지 빼지 않을지를 결정해야겠네요! 😄 

<리액트가 jsx 변수와 컴포넌트 렌더를 어떻게 다르게 취급하는지>에 대해서는 gpt에게 물어봤더니

_JSX 변수는 단순히 JavaScript 변수일 뿐이며, React 컴포넌트가 아닙니다. 따라서 컴포넌트 라이프사이클이나 상태를 관리할 수 없습니다. 반면, 컴포넌트는 React 엘리먼트를 생성하고, 상태(state)를 관리하며, 라이프사이클 메서드를 사용하여 컴포넌트 생명주기를 관리할 수 있습니다._

(1) 내부에 상태를 가질 수 있는지, (2) 리액트 컴포넌트 라이프사이클 메서드를 사용할 수 있는지 --> 이렇게 두가지 측면에서의 차이가 있다고 말하는거 같은데 이게 태희님이 맨 마지막에 말씀하신 부분의 뜻이 맞을까요?

2024-04-14 11:45 UTC, twinstae commented on app/multi-step-form/_components/FormContainer.tsx
> +  const leftNavigation = (
역할을 기준으로 나눈다는 것도 역할이 그러면 어떤 것들이 있고, 나눌 때 비용이 무엇인지를 알아야 해서 단순한 기준은 아닙니다.

그리고 GPT에게 이러한 고민에 대한 질문을 하는 건 보통 안 좋다는 생각이 듭니다. ^^;;; 라이프 사이클 메서드 는 클래스 컴포넌트에만 쓰는 건데. 그러면 함수 컴포넌트에서는 어떻게 볼 것이며. useState가 없는 컴포넌트라도 나눌 이유가 충분히 있기 때문입니다.

2024-04-14 11:49 UTC, JunnieLee commented on app/multi-step-form/_components/FormStepThree.tsx
> +            <section className={styles.column}>
**"h4가 누구의 제목인지 생각해보면 저 라벨, 체크박스의 이름입니다. 이미 라벨 3개가 서로를 구분하고 있기 때문에 section을 쓰지 않아도 구분이 됩니다."** <- 아아 요 말씀 들으니 바로 이해가 됐어요!!!! 말씀주신대로 제가 section의 설명을 기계적으로 받아들여서 생긴 오해인것같네요 ㅎㅎ 기계들은 이미 label과 그 안의 h4 로 의미적 구분이 된 상태이니, section 대신 div를 써서 스타일 처리만 해주면 되는거군요?!

(다시 생각해보니 오히려 불필요하게 여기저기 시멘틱 태그를 다 갖다붙이려 하면 기계가 더 혼란스러워 할것같기도 합니다 🤣 적재적소에 딱 필요한 시맨틱들만 갖다 써야겠네요)

2024-04-14 11:51 UTC, JunnieLee commented on app/multi-step-form/_components/FormStepThree.tsx
> +            <section className={styles.column}>
✅ 수정완료 ([커밋 링크](https://github.com/JunnieLee/web-standards-considered-components/pull/2/commits/162975da90f36ac9e39286ac07c5b90255082b64))

2024-04-14 11:55 UTC, twinstae commented on app/multi-step-form/_components/FormContainer.tsx
> +          router.push("/multi-step-form?step=1");
저는 웹에서는 보통 router.back 이 기본값으로는 좋다고 생각합니다. 그 동작이 마음에 들지 않는 경우에는... 웹의 히스토리 스택 구조를 포기하고 직접 재창조를 해야 합니다. 당근의 스택 플로우 같은 게 그런 친구들인데요.

하지만 이러면 URL을 공유하거나 하지 못하게 되는 단점도 있고요. 안드로이드 백 버튼 동작을 구독한다거나 하는 기술도 필요한데. 웹뷰가 아니면 이게 크로미움 브라우저에서만 지원되고 있어서 여러모로 눈물이 납니다.

프롬도 스토어는 웹 히스토리 동작을 그대로 따라갔지만, 프롬 채널은 스택 네비게이션 로직을 밑바닥부터 재창조했습니다...

2024-04-14 11:57 UTC, twinstae commented on app/multi-step-form/_components/FormContainer.tsx
> +  const leftNavigation = (
함수나 상수나 jsx 같은 건 이러쿵 저러쿵 보통 컴포넌트 안에 변수로 정의하면 안 좋습니다. 바깥에 정의하는 게 좋죠.

2024-04-14 12:03 UTC, twinstae commented on app/multi-step-form/_components/FormStepThree.tsx
> +            <section className={styles.column}>
넹. 사실 section을 여기저기에 붙이는 건 시맨틱하지 않은 거라. 표준 문장을 내 생각대로 해석하기보다는, 실제로 모범적인 웹 마크업의 구조나 모양을 살펴보시면 좋습니다. 그러면 좋은 감이 생기거든요. 표준의 어쩌구 문장보다 "아니 이거 좀 이상한데?" 라는 생각이 먼저 드는 게 정상입니다.

2024-04-14 13:22 UTC, JunnieLee commented on app/multi-step-form/_components/FormStepOne.tsx
> +      aria-current={step === 1 ? "step" : "false"}
✅ 수정완료 ([커밋 링크](https://github.com/JunnieLee/web-standards-considered-components/pull/2/commits/26ead48f76b5c5c27a95a2af2f5228eda1cd62fa))

---
태희님, 일단 위와 같이 바꿔보았는데요, 뭔가 최선이 아닌것같은 느낌도 듭니다 ^^; 공통적인 부분은 하나로 따로 빼서 중복을 줄였지만, 어째 더 복잡도가 올라가 보이기도 하는데, 혹시 이와 관련해 추가적으로 코멘트 주실 수 있는 부분이 있을까요~? 🐱 @twinstae

2024-04-14 13:33 UTC, JunnieLee commented on app/multi-step-form/_components/formContainer.module.css
> +.hidden {
1. 그렇네요 흠,,,그럼 hide-in-sr-only 같은 이름으로 바꾸면 좀더 명확할까요?! 😄 
2. 맞아요 그래서 global에다가 놓고 싶은데... global.css 는 css module이랑 또 다른 형태로 되어있어서 실은 글로벌 적으로 저런 스타일을 가진 class를 만들고싶은데 그걸 어떻게 해야할지 잘 모르겠어서 저렇게 임시방편으로 로컬 css 모듈에 넣어놨었습니다 😭 흠.. 요 방법은 제가 좀더 찾아보겠습니다!!! 🙇

2024-04-14 13:42 UTC, JunnieLee commented on app/globals.css
> +label:has(input[type="radio"]:checked) {
✅ 수정완료 ([커밋 링크](https://github.com/JunnieLee/web-standards-considered-components/pull/2/commits/c45fb0ce467a2713aa12039c1d86ce41d2f2ab7f))

2024-04-14 13:46 UTC, JunnieLee commented on app/multi-step-form/_components/formContainer.module.css
> +  font-weight: 600;
흠.. 어떤 말씀인지 이해됐습니다..! 약간 사람이 눈으로 보면 이해할 수 있지만 기계가 읽기에는 (=스크린 리더로만 스크린을 볼 수 있는 시각 장애인 분들이 이해하기에는) 어려운 구조긴 하군요..!!

그럼 이거는 말씀대로 아예 checkbox가 아닌 radio input으로 아예 좀 개조를 해줘야할 필요가 있겠습니다 ㅎㅎ....! 가운데 친구를 클릭했을 때 radio 토글은 어떻게 하면 좋을지까지 해서 조금 더 고민이 필요할꺼같습니다! 라디오 인풋으로 바꾸면서 그부분까지 한번 고민해볼게요!~ 👍 ✨ 완료되면 요기 쓰레드에다가 확인 댓글 남기겠슴다!

2024-04-17 14:03 UTC, JunnieLee commented
## To-do :

1) step 2 토글 부분 -> 체크박스가 아닌 라디오 인풋으로 바꾸기 
2) css module hidden 클래스 이름 바꾸기 + 글로벌 범위에서 쓸 수 있도록 바꾸기

-> 얘네 둘은 그 다음 PR에서 포함해 작업하겠습니다!

2024-04-17 14:03 UTC, merged